### ISSUE TITLE
something wrong when adj.cuda() 

### ISSUE THREAD

**Issue by liyingjack** [ycq091044/Hypergraph-Learning-with-Line-Expansion#1]
The LE is very interesting and novel method to model higher-order relationship in hypergraph.  There are something wrong when i run the LEGCN code like this:

```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/pytorch/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/envs/pytorch/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.python-2022.17.13051012/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.python-2022.17.13051012/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.python-2022.17.13051012/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/root/.vscode-server/extensions/ms-python.python-2022.17.13051012/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/root/.vscode-server/extensions/ms-python.python-2022.17.13051012/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/root/.vscode-server/extensions/ms-python.python-2022.17.13051012/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/opt/workspace/lyl/code/LEGCN/src/main.py", line 48, in <module>
    adj = adj.cuda()
  File "/opt/anaconda3/envs/pytorch/lib/python3.9/site-packages/scipy/sparse/_base.py", line 771, in __getattr__
    raise AttributeError(attr + " not found")
AttributeError: cuda not found
```

The reason of this error is that the type of adj returned from `load_data()` is not tensor, the adj.cuda() cannot work after `load_data()`.
I found the adj was convert to tensor is the position of `# model definition`, so we can execute adj.cuda() here instead of the position of `load_data()` to fix the error. The repaired code is as follows:

```
# model definition
if args.modelType == 0:
    adj = sparse_mx_to_torch_sparse_tensor(adj)
    if args.cuda:
        adj = adj.cuda()
    model = GCN(nfeat=features.shape[1],
                nhid=args.hidden,
                nclass=labels.max().item() + 1,
                dropout=args.dropout)   
elif args.modelType == 1:
    adj = torch.FloatTensor(np.array(adj.todense()))
    if args.cuda:
        adj = adj.cuda()
    model = SpGAT(nfeat=features.shape[1],
                nhid=args.hidden,
                nclass=labels.max().item() + 1,
                dropout=args.dropout)
elif args.modelType == 2:
    adj = torch.FloatTensor(np.array(adj.todense()))
    if args.cuda:
        adj = adj.cuda()
    model = GAT(nfeat=features.shape[1],
                nhid=args.hidden,
                nclass=labels.max().item() + 1,
                dropout=args.dropout)
```

**Comment by ycq091044** [comment]
Thanks for the findings. I have sent a push to fix it.

**Comment by liyingjack** [comment]
You're so efficient! There is another small mistake in main.py.
Line 112 in main.py should be `PvT = PvT.cuda()`.
`PvT` was mistakenly written as `Pvp`
